 --  Include all the following statements, using comments to highlight when one is
-- being addressed and include an explanation of their implementation.
--
--  One UPDATE or one DELETE combined with a subquery
--  One selection function CASE/DECODE
--  One INNER JOIN using a GROUP function
--  One LEFT OUTER JOIN
--  One RIGHT OUTER JOIN
--  One UNION
--  One INTERSECT
--  One VIEW
